version: '3.1'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - 8081:8081

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1OyTiUOIlAenAaHV
      MYSQL_DATABASE: SpringKosmoCalc

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8889:80
    environment:
      - PMA_ARBITRARY=1